name: Check NVM Availability

on:
  push:
    branches:
      - main  # Adjust this as necessary for your repository
  pull_request:
    branches:
      - main  # Adjust this as necessary for your repository


jobs:
  check-nvm-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Check nvm on Ubuntu
      run: |
        echo "Checking nvm on Ubuntu..."
        command -v nvm && nvm --version || echo "nvm not available"

  check-nvm-windows:
    runs-on: windows-latest
    steps:
    - name: Check nvm on Windows
      run: |
        echo "Checking nvm on Windows..."
        if (Get-Command nvm -ErrorAction SilentlyContinue) {
          nvm --version
        } else {
          echo "nvm not available"
        }
      shell: pwsh

