name: Set GH Status

on:
  push:
    branch: master
  schedule:
    - cron: '0 * * * *'

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
        run: "set-gh-status -m '{#} pending notifications' -e :heart:"
        env:
          SET_STATUS_TOKEN: ${{ secrets.SET_STATUS_TOKEN}}
