name: Set GH Status

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/30 * * * *'

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeal/npx@master
        env:
          SET_STATUS_TOKEN: ${{ secrets.SET_STATUS_TOKEN}}
        with:
          args: "set-gh-status -m '{#} pending notifications' -e :heart:"
